variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:3-jdk-11

cache:
  paths:
    - .m2/repository

before_script:
  - curl -fL https://install-cli.jfrog.io | sh
  - jf c add artifactory --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --access-token=$ARTIFACTORY_TOKEN --interactive=false
  - jf c s
  - jf mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false

build:
  stage: build
  script:
    - jf mvn clean package
    - jf mvn deploy --project=hello --build-name=hello-maven-gitlab --build-number=$CI_JOB_ID
    - jf rt bce --project=hello hello-maven-gitlab $CI_JOB_ID
    - jf rt bag --project=hello hello-maven-gitlab $CI_JOB_ID .
    - jf rt bp --project=hello hello-maven-gitlab $CI_JOB_ID
