variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:3-jdk-11

cache:
  paths:
    - .m2/repository

before_script:
  - curl -fL https://install-cli.jfrog.io | sh
  - jf c add artifactory --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
  - jf c use artifactory
  - jf c s
  - jf mvnc --repo-deploy-releases=$REPO_NAME --repo-deploy-snapshots=$REPO_NAME --repo-resolve-releases=$REPO_NAME --repo-resolve-snapshots=$REPO_NAME
  - jf mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false

build:
  stage: build
  script:
    - jf mvn clean package
    - jf mvn deploy --build-name=$BUILD_NAME --build-number=$CI_JOB_ID
    - jf rt bce $BUILD_NAME $CI_JOB_ID
    - jf rt bag $BUILD_NAME $CI_JOB_ID
    - jf rt bp $BUILD_NAME $CI_JOB_ID
